julia plot_result.jl ../results/county_income_00 &
julia plot_result.jl ../results/county_education_00 &
julia plot_result.jl ../results/county_unemployment_00 &
julia plot_result.jl ../results/county_election_00 &
julia plot_result.jl ../results/ward_edu_00 &
julia plot_result.jl ../results/ward_age_00 &
julia plot_result.jl ../results/ward_income_00 &
julia plot_result.jl ../results/ward_election_00 &
julia plot_result.jl ../results/cora_04_00 &
julia plot_result.jl ../results/cora_08_00 &
julia plot_result.jl ../results/cora_16_00 &
julia plot_result.jl ../results/cora_32_00 &
julia plot_result.jl ../results/cora_64_00 &
julia plot_result.jl ../results/cora_ff_00 &
